//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzureTracker.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.11.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("your organization name")]
        public string Organization {
            get {
                return ((string)(this["Organization"]));
            }
            set {
                this["Organization"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("your azure PAT")]
        public string PAT {
            get {
                return ((string)(this["PAT"]));
            }
            set {
                this["PAT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Bug;User Story;Task;Epic;Feature")]
        public string WorkItemTypes {
            get {
                return ((string)(this["WorkItemTypes"]));
            }
            set {
                this["WorkItemTypes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public double BuildNotOlderThanDays {
            get {
                return ((double)(this["BuildNotOlderThanDays"]));
            }
            set {
                this["BuildNotOlderThanDays"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"
                  {
                  ""defaultfilters"": [
                  {
                  ""type"": ""WorkItem"",
                  ""fields"": [
                  {
                  ""Status"": ""Active;New;Ready""
                  }
                  ]
                  },
                  {
                  ""type"": ""PR"",
                  ""fields"": [
                  {
                  ""IsDraft"": ""false""
                  },
                  {
                  ""Status"": ""Active""
                  }
                  ]
                  },
                  {
                  ""type"": ""Build"",
                  ""fields"": [
                  {
                  ""RepoName"": ""Repo1;Repo2;Repo3""
                  }
                  ]
                  }
                  ]
                  }")]
        public string DefaultFilters {
            get {
                return ((string)(this["DefaultFilters"]));
            }
            set {
                this["DefaultFilters"] = value;
            }
        }
    }
}
